//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiYou.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiYou.Shared.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor uw bericht via ons contactformulier. Wij nemen zo snel mogelijk contact met u op..
        /// </summary>
        public static string Email_ContactConfirmation_Body {
            get {
                return ResourceManager.GetString("Email_ContactConfirmation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} MiYou - Alle rechten voorbehouden..
        /// </summary>
        public static string Email_ContactConfirmation_Footer {
            get {
                return ResourceManager.GetString("Email_ContactConfirmation_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo {0},.
        /// </summary>
        public static string Email_ContactConfirmation_Greeting {
            get {
                return ResourceManager.GetString("Email_ContactConfirmation_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot aan de rand van het universum - of gewoon uw inbox 😉!.
        /// </summary>
        public static string Email_ContactConfirmation_Signoff {
            get {
                return ResourceManager.GetString("Email_ContactConfirmation_Signoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij hebben uw bericht ontvangen.
        /// </summary>
        public static string Email_ContactConfirmation_Title {
            get {
                return ResourceManager.GetString("Email_ContactConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact bevestiging.
        /// </summary>
        public static string Email_Title_ContactConfirm {
            get {
                return ResourceManager.GetString("Email_Title_ContactConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email kon niet worden bereikt. Heeft u het goede email adres ingevuld?.
        /// </summary>
        public static string Error_Contact_EmailDeliveryFailed {
            get {
                return ResourceManager.GetString("Error_Contact_EmailDeliveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is helaas al contact gemaakt met ons via dit email adres..
        /// </summary>
        public static string Error_Contact_EmailExists {
            get {
                return ResourceManager.GetString("Error_Contact_EmailExists", resourceCulture);
            }
        }
    }
}
